{application,dotenvy,
             [{modules,['Elixir.Dotenvy','Elixir.Dotenvy.Parser',
                        'Elixir.Dotenvy.Parser.Opts',
                        'Elixir.Dotenvy.Transformer',
                        'Elixir.Dotenvy.Transformer.Error']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A port of the original dotenv Ruby gem, for mix and releases.\nFacilitates runtime config per the 12-factor App.\n"},
              {registered,[]},
              {vsn,"0.7.0"}]}.
