import Config

# Configure your database
config :przma, Przma.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "172.235.17.68",
  database: "przma_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :przma, PrzmaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "QUw67RWrq9OAyzoXDZIz8WzSwllfq0/Pm18wAuJWdtL8zp99rcAND/f0KcCyKV61",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:api, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:api, ~w(--watch)]}
  ]
# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.


config :przma, PrzmaWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/przma_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]
  # watchers: [
  #   esbuild: {Esbuild, :install_and_run, [:api, ~w(--sourcemap=inline --watch)]},
  #   tailwind: {Tailwind, :install_and_run, [:api, ~w(--watch)]}
  # ]
# Enable dev routes for dashboard and mailbox
config :przma, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20


config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true




# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false


config :przma, Przma.Auth.Token,
  secret_key: "5UjFeyWvHFAEVyeeVTJm6Hul6vrc5602oBhU2xcMFPN9vpZGdahWHy6BnAtm3bTA",
  access_token_ttl: 900,        # 15 minutes
  refresh_token_ttl: 604_800    # 7 days
